---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: focal
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        install_python3: false
        install_corosync: false

        haproxy_ssl_deploy: true
        haproxy_ssl_source: molecule/default/files/ssl
        haproxy_stats: true

        haproxy_frontends:
          - name: main-http
            description: Front-end for all HTTP/S traffic
            bind:
              - listen: 0.0.0.0:80
              - listen: 0.0.0.0:443
                param:
                  - ssl crt {{ haproxy_ssl_dir }}
            mode: http
            config:
              - default_backend default

        haproxy_backends:
          - name: default
            mode: http
            config:
              - http-request set-header Server haproxy
              - http-request return status 200 content-type text/html file /etc/haproxy/static/default.html


verifier:
  name: ansible
